source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'airbrake'
gem 'angular-rails-templates'
gem 'angularjs-rails'
gem 'bootstrap-sass', '~> 3.3.0'
gem 'byebug', '3.5.1', group: :development
gem 'carmen'
gem 'coffee-rails', '~> 4.0.0'
gem 'comfortable_mexican_sofa', '~> 1.12.0'
gem 'devise'
gem 'devise_token_auth'
gem 'fog'
gem 'gibbon', '1.1.5'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'letter_opener', :group => :development
gem 'liquid'
gem 'newrelic_rpm'
gem 'ng-rails-csrf'
gem 'oj'
gem 'oj_mimic_json'
gem 'omniauth'
gem 'paperclip'
gem 'pg'
gem 'pry', group: :development
gem 'rack-cors', :require => 'rack/cors'
gem 'rails', '4.2.4'
gem 'rails-observers'
gem 'rails_12factor', group: :production
gem 'sass', '~> 3.3.0'
gem 'sass-rails', '~> 5.0.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'sidekiq'
gem 'sinatra'
gem 'spring',        group: :development
gem 'stripe'
gem 'stripe_event'
gem 'time_difference'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'websocket-rails'
gem 'will_paginate'
gem 'dalli'
gem 'puma', group: :production