default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: leaderboard_development

test:
  <<: *default
  database: leaderboard_test

production:
  <<: *default
  database: leaderboard_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
